-- ФИНАЛЬНЫЙ ФИКС СХЕМЫ (ИЗБЕГАЕМ КОНФЛИКТА ИМЕН)
-- Выполни этот код в SQL Editor в Supabase

-- Удаляем старые таблицы (Внимание: это очистит данные!)
DROP TABLE IF EXISTS marriages CASCADE;
DROP TABLE IF EXISTS proposals CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS profiles CASCADE;

-- 1. Таблица Профилей (вместо users, чтобы избежать конфликта с системными именами)
CREATE TABLE profiles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  handle TEXT UNIQUE NOT NULL,
  avatar_url TEXT,
  silk INTEGER DEFAULT 100,
  role TEXT DEFAULT 'Моногам',
  status TEXT DEFAULT 'Свободен',
  telegram_id BIGINT,
  notify_proposals BOOLEAN DEFAULT true,
  notify_marriages BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Таблица Предложений
CREATE TABLE proposals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_handle TEXT REFERENCES profiles(handle) ON DELETE CASCADE,
  to_handle TEXT REFERENCES profiles(handle) ON DELETE CASCADE,
  status TEXT DEFAULT 'pending',
  ring_id TEXT DEFAULT 'basic',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Таблица Браков
CREATE TABLE marriages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  partner_a TEXT REFERENCES profiles(handle) ON DELETE CASCADE,
  partner_b TEXT REFERENCES profiles(handle) ON DELETE CASCADE,
  wedding_style TEXT DEFAULT 'Кибер-ЗАГС',
  ring_id TEXT DEFAULT 'basic',
  hype_score BIGINT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Таблица голосов за Хайп
CREATE TABLE IF NOT EXISTS marriage_votes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  marriage_id BIGINT REFERENCES marriages(id) ON DELETE CASCADE,
  voter_handle TEXT REFERENCES profiles(handle) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(marriage_id, voter_handle)
);

-- 4. Таблица кэша аватарок (для get-avatar.js)
CREATE TABLE IF NOT EXISTS threads_avatars_cache (
  username TEXT PRIMARY KEY,
  avatar_url TEXT NOT NULL,
  cached_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Таблица ручных правок (для get-avatar.js)
CREATE TABLE IF NOT EXISTS users_errors (
  username TEXT PRIMARY KEY,
  avatar_url TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ГАРАНТИРОВАННОЕ ВКЛЮЧЕНИЕ REALTIME
DROP PUBLICATION IF EXISTS supabase_realtime;
CREATE PUBLICATION supabase_realtime FOR TABLE profiles, proposals, marriages, threads_avatars_cache, marriage_votes;

-- ВКЛЮЧАЕМ REPLICA IDENTITY FULL
ALTER TABLE profiles REPLICA IDENTITY FULL;
ALTER TABLE proposals REPLICA IDENTITY FULL;
ALTER TABLE marriages REPLICA IDENTITY FULL;
ALTER TABLE marriage_votes REPLICA IDENTITY FULL;

-- ВЫКЛЮЧАЕМ RLS ДЛЯ MVP
ALTER TABLE profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE proposals DISABLE ROW LEVEL SECURITY;
ALTER TABLE marriages DISABLE ROW LEVEL SECURITY;
ALTER TABLE marriage_votes DISABLE ROW LEVEL SECURITY;
