-- ФИНАЛЬНЫЙ ФИКС СХЕМЫ (ИЗБЕГАЕМ КОНФЛИКТА ИМЕН)
-- Выполни этот код в SQL Editor в Supabase

-- Удаляем старые таблицы (Внимание: это очистит данные!)
-- DROP TABLE IF EXISTS pets CASCADE;
-- DROP TABLE IF EXISTS marriage_votes CASCADE;
-- DROP TABLE IF EXISTS marriages CASCADE;
-- DROP TABLE IF EXISTS proposals CASCADE;
-- DROP TABLE IF EXISTS users CASCADE;
-- DROP TABLE IF EXISTS profiles CASCADE;

-- 1. Таблица Профилей (вместо users, чтобы избежать конфликта с системными именами)
CREATE TABLE IF NOT EXISTS profiles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  handle TEXT UNIQUE NOT NULL,
  avatar_url TEXT,
  silk INTEGER DEFAULT 100,
  role TEXT DEFAULT 'Моногам',
  status TEXT DEFAULT 'Свободен',
  telegram_id BIGINT,
  notify_proposals BOOLEAN DEFAULT true,
  notify_marriages BOOLEAN DEFAULT true,
  last_daily_claim TIMESTAMPTZ,      -- Время последнего сбора ежедневной награды
  streak_days INTEGER DEFAULT 0,     -- Сколько дней подряд заходил
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Добавляем колонки в существующую таблицу, если они еще не существуют (безопасное обновление)
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS last_daily_claim TIMESTAMPTZ;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS streak_days INTEGER DEFAULT 0;

-- 2. Таблица Предложений
CREATE TABLE IF NOT EXISTS proposals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_handle TEXT REFERENCES profiles(handle) ON DELETE CASCADE,
  to_handle TEXT REFERENCES profiles(handle) ON DELETE CASCADE,
  status TEXT DEFAULT 'pending',
  ring_id TEXT DEFAULT 'basic',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Таблица Браков
CREATE TABLE IF NOT EXISTS marriages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  partner_a TEXT REFERENCES profiles(handle) ON DELETE CASCADE,
  partner_b TEXT REFERENCES profiles(handle) ON DELETE CASCADE,
  wedding_style TEXT DEFAULT 'Кибер-ЗАГС',
  ring_id TEXT DEFAULT 'basic',
  hype_score BIGINT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Таблица голосов за Хайп
CREATE TABLE IF NOT EXISTS marriage_votes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  marriage_id BIGINT REFERENCES marriages(id) ON DELETE CASCADE,
  voter_handle TEXT REFERENCES profiles(handle) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(marriage_id, voter_handle)
);

-- 5. Таблица питомцев (Тамагочи) для браков
CREATE TABLE IF NOT EXISTS pets (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  marriage_id BIGINT UNIQUE REFERENCES marriages(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  health INTEGER DEFAULT 100,
  happiness INTEGER DEFAULT 100,
  last_fed_at TIMESTAMPTZ DEFAULT NOW(),
  last_played_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Таблица кэша аватарок (для get-avatar.js)
CREATE TABLE IF NOT EXISTS threads_avatars_cache (
  username TEXT PRIMARY KEY,
  avatar_url TEXT NOT NULL,
  cached_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Таблица ручных правок (для get-avatar.js)
CREATE TABLE IF NOT EXISTS users_errors (
  username TEXT PRIMARY KEY,
  avatar_url TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ГАРАНТИРОВАННОЕ ВКЛЮЧЕНИЕ REALTIME
DROP PUBLICATION IF EXISTS supabase_realtime;
CREATE PUBLICATION supabase_realtime FOR TABLE profiles, proposals, marriages, threads_avatars_cache, marriage_votes, pets;

-- ВКЛЮЧАЕМ REPLICA IDENTITY FULL
ALTER TABLE profiles REPLICA IDENTITY FULL;
ALTER TABLE proposals REPLICA IDENTITY FULL;
ALTER TABLE marriages REPLICA IDENTITY FULL;
ALTER TABLE marriage_votes REPLICA IDENTITY FULL;
ALTER TABLE pets REPLICA IDENTITY FULL;

-- ВЫКЛЮЧАЕМ RLS ДЛЯ MVP
ALTER TABLE profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE proposals DISABLE ROW LEVEL SECURITY;
ALTER TABLE marriages DISABLE ROW LEVEL SECURITY;
ALTER TABLE marriage_votes DISABLE ROW LEVEL SECURITY;
ALTER TABLE pets DISABLE ROW LEVEL SECURITY;
