-- ФИНАЛЬНЫЙ ФИКС СХЕМЫ (ИЗБЕГАЕМ КОНФЛИКТА ИМЕН)
-- Выполни этот код в SQL Editor в Supabase

-- Удаляем старые таблицы (Внимание: это очистит данные!)
DROP TABLE IF EXISTS marriages CASCADE;
DROP TABLE IF EXISTS proposals CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS profiles CASCADE;

-- 1. Таблица Профилей (вместо users, чтобы избежать конфликта с системными именами)
CREATE TABLE profiles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  handle TEXT UNIQUE NOT NULL,
  avatar_url TEXT,
  silk INTEGER DEFAULT 100,
  role TEXT DEFAULT 'Моногам',
  status TEXT DEFAULT 'Свободен',
  telegram_id BIGINT,
  notify_proposals BOOLEAN DEFAULT true,
  notify_marriages BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Таблица Предложений
CREATE TABLE proposals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_handle TEXT REFERENCES profiles(handle) ON DELETE CASCADE,
  to_handle TEXT REFERENCES profiles(handle) ON DELETE CASCADE,
  status TEXT DEFAULT 'pending',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Таблица Браков
CREATE TABLE marriages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  partner_a TEXT REFERENCES profiles(handle) ON DELETE CASCADE,
  partner_b TEXT REFERENCES profiles(handle) ON DELETE CASCADE,
  wedding_style TEXT DEFAULT 'Кибер-ЗАГС',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ГАРАНТИРОВАННОЕ ВКЛЮЧЕНИЕ REALTIME
DROP PUBLICATION IF EXISTS supabase_realtime;
CREATE PUBLICATION supabase_realtime FOR TABLE profiles, proposals, marriages;

-- ВКЛЮЧАЕМ REPLICA IDENTITY FULL
ALTER TABLE profiles REPLICA IDENTITY FULL;
ALTER TABLE proposals REPLICA IDENTITY FULL;
ALTER TABLE marriages REPLICA IDENTITY FULL;

-- ВЫКЛЮЧАЕМ RLS ДЛЯ MVP
ALTER TABLE profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE proposals DISABLE ROW LEVEL SECURITY;
ALTER TABLE marriages DISABLE ROW LEVEL SECURITY;
